# -*- coding: utf-8 -*-
"""Customer Churn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v61yA1qCmlFngzt3SjwKWPpD4QcI2vSi
"""

# Import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

import warnings
warnings.filterwarnings("ignore")

# Upload Dataset
from google.colab import files

uploaded = files.upload()

# Load Dataset
df = pd.read_excel("Telco_customer_churn.xlsx")
df.head()

df.shape

df.info()

# ubah jadi numerik
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors="coerce")

df.describe()

df.columns

# Cek Missing Value
df.isnull().sum()

# tangani missing value
df["Churn Reason"] = df["Churn Reason"].fillna("Not Churned")
df["Total Charges"].fillna(df["Total Charges"].median(), inplace=True)

# cek duplikat
df.duplicated().sum()

"""**EDA**"""

# buat folder untuk menyimpan hasil visualisasi.
import os

os.makedirs("images", exist_ok=True)

# Visualisasi 1 — Churn Distribution
plt.figure(figsize=(6,5))

sns.countplot(data=df, x="Churn Label")

plt.title("Customer Churn Distribution")
plt.xlabel("Churn Status")
plt.ylabel("Number of Customers")

plt.savefig("images/churn_distribution.png", dpi=300, bbox_inches="tight")

plt.show()

# Visualisasi 2 — Gender Distribution
plt.figure(figsize=(6,5))

sns.countplot(data=df, x="Gender")

plt.title("Customer Distribution by Gender")

plt.savefig("images/gender_distribution.png", dpi=300, bbox_inches="tight")

plt.show()

# Visualisasi 3 — Contract Type
plt.figure(figsize=(7,5))

sns.countplot(data=df, x="Contract")

plt.title("Customer Distribution by Contract Type")
plt.xticks(rotation=10)

plt.savefig("images/contract_type.png", dpi=300, bbox_inches="tight")

plt.show()

# Visualisasi 4 — Churn by Contract
plt.figure(figsize=(8,5))

sns.countplot(data=df, x="Contract", hue="Churn Label")

plt.title("Customer Churn by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Number of Customers")

plt.savefig("images/churn_by_contract.png", dpi=300, bbox_inches="tight")

plt.show()

# Visualisasi 5 — Monthly Charges by Churn
plt.figure(figsize=(8,5))

sns.boxplot(data=df, x="Churn Label", y="Monthly Charges")

plt.title("Monthly Charges by Churn Status")

plt.savefig("images/monthly_charges_churn.png", dpi=300, bbox_inches="tight")

plt.show()

# Visualisasi 6 — Tenure Distribution
plt.figure(figsize=(8,5))

sns.histplot(df["Tenure Months"], bins=20)

plt.title("Customer Tenure Distribution")

plt.savefig("images/tenure_distribution.png", dpi=300, bbox_inches="tight")

plt.show()

# Visualisasi 7 — Internet Service vs Churn
plt.figure(figsize=(8,5))

sns.countplot(data=df,
              x="Internet Service",
              hue="Churn Label")

plt.title("Internet Service by Churn")

plt.savefig("images/internet_service_churn.png",
            dpi=300,
            bbox_inches="tight")

plt.show()

# Visualisasi 8 — Payment Method vs Churn
plt.figure(figsize=(10,5))

sns.countplot(data=df,
              y="Payment Method",
              hue="Churn Label")

plt.title("Payment Method by Churn")

plt.savefig("images/payment_method_churn.png",
            dpi=300,
            bbox_inches="tight")

plt.show()

# Visualisasi 9 — Correlation Heatmap
plt.figure(figsize=(8,6))

numeric = df.select_dtypes(include=["int64","float64"])

sns.heatmap(numeric.corr(),
            annot=True,
            cmap="coolwarm")

plt.title("Correlation Heatmap")

plt.savefig("images/correlation_heatmap.png",
            dpi=300,
            bbox_inches="tight")

plt.show()

# Visualisasi 10 — Top Churn Reasons
top_reason = (
    df[df["Churn Label"]=="Yes"]["Churn Reason"]
      .value_counts()
      .head(10)
)

plt.figure(figsize=(10,6))

sns.barplot(
    x=top_reason.values,
    y=top_reason.index
)

plt.title("Top 10 Customer Churn Reasons")

plt.savefig("images/top_churn_reasons.png",
            dpi=300,
            bbox_inches="tight")

plt.show()